name: CI Pipeline with DVC

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]


jobs:
  dvc-check:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3️⃣ Install DVC
      - name: Install DVC
        run: |
          python -m pip install --upgrade pip
          pip install dvc[all]

      # 4️⃣ Configure DVC remote authentication (optional)
      # For example, if you use Google Drive:
      # env:
      #   GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

      # 5️⃣ Pull your tracked data from remote
      - name: Pull DVC data
        run: |
          dvc pull || echo "No remote data found or not required for this run."

      # 6️⃣ Verify DVC tracking status
      - name: Verify DVC status
        run: |
          dvc status

      # 7️⃣ List data files after pull (verification)
      - name: List repository contents
        run: |
          ls -R
  test-lint:
    runs-on: ubuntu-latest
    needs: dvc-check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Lint Python files
        run: flake8 . --ignore=E501,W503

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q
